# Optimized for debugging.
# For deploying to a server, use docker-compose-deploy.yml

version: "3.9"

services:
  plugin:
    container_name: chemical-interactions-plugin
    build:
      dockerfile: docker/Dockerfile
    environment:
      NTS_HOST: ${NTS_HOST:-}
      NTS_PORT: ${NTS_PORT:-}
      ARGS: ${ARGS:-}
      INTERACTIONS_URL: http://arpeggio:8000
    command: python -X dev chem_interactions/run.py -r -v ${ARGS}
    stdin_open: true
    tty: true
    volumes:
      - ".:/app"
