# Optimized for debugging.

version: "3.9"

services:
  plugin:
    build:
      context: chem_interactions
    environment:
      NTS_HOST: ${NTS_HOST:-}
      NTS_PORT: ${NTS_PORT:-}
      ARGS: ${ARGS:-}
      INTERACTIONS_URL: http://arpeggio:8000
    command: python run.py ${ARGS}
    stdin_open: true
    tty: true
    volumes:
      - "./chem_interactions:/app"
      # - "../nanome-lib/nanome:/opt/conda/lib/python3.7/site-packages/nanome"
    depends_on:
      - arpeggio
  arpeggio:
    build:
      context: arpeggio-service
    ports:
      - 8000:8000
    environment:
      FLASK_ENV: development
      FLASK_APP: wsgi.py
    stdin_open: true
    tty: true
    volumes:
      - "./arpeggio-service:/app"
