# Compose file to deploy plugin on a server

version: "3.9"

services:
  chemical-interactions:
    restart: always
    build:
      context: .
    environment:
      NTS_HOST: ${NTS_HOST:-}
      NTS_PORT: ${NTS_PORT:-}
      ARGS: ${ARGS:-}
    command: python run.py ${ARGS}
