# Optimized for debugging.

version: "3.9"

services:
  plugin:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      NTS_HOST: ${NTS_HOST:-nts-dev.nanome.ai}
      NTS_PORT: ${NTS_PORT:-9999}
      INTERACTIONS_URL: http://arpeggio:8000
    stdin_open: true
    tty: true
    # volumes:
    #   - ":/app"
  arpeggio:
    build:
      context: arpeggio-service
    ports:
      - 8000:8000
    environment:
      FLASK_ENV: development
    command: python app.py
    stdin_open: true
    tty: true
    # volumes:
    #   - "arpeggio-service:/app"

    
