# Optimized for debugging.

version: "3.9"

services:
  plugin:
    build:
      context: nanome_chemical_interactions
    environment:
      NTS_HOST: ${NTS_HOST:-nts-dev.nanome.ai}
      NTS_PORT: ${NTS_PORT:-9999}
      INTERACTIONS_URL: http://arpeggio:8000
    stdin_open: true
    tty: true
    volumes:
      - "./nanome_chemical_interactions:/app"
    depends_on:
      - arpeggio
  arpeggio:
    build:
      context: arpeggio-service
    ports:
      - 5000:5000
    environment:
      FLASK_ENV: development
      FLASK_APP: wsgi.py
    stdin_open: true
    tty: true
    volumes:
      - "./arpeggio-service:/app"
    command: gunicorn --preload -w 4 -b 127.0.0.1:5000 wsgi:app
