version: "3.9"

services:
  plugin:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      HOST: ${HOST:-plugins.nanome.ai}
      PORT: ${PORT:-9999}
      INTERACTIONS_URL: http://server:8000
    volumes:
      - ".:/app"
  
  server:
    build:
      context: arpeggio-service
    ports:
      - 8000:8000
    environment:
      FLASK_ENV: development
    command: python app.py
    stdin_open: true
    tty: true
    volumes:
      - "./arpeggio-service:/app"

    
