# Optimized for debugging.

version: "3.9"

services:
  plugin:
    container_name: chemical-interactions
    build:
      dockerfile: docker/Dockerfile
    environment:
      NTS_HOST: ${NTS_HOST:-}
      NTS_PORT: ${NTS_PORT:-}
      ARGS: ${ARGS:-}
    command: python -X dev run.py -r -v ${ARGS}
    stdin_open: true
    tty: true
    volumes:
      - ".:/app"
