version: "3.9"

services:
  plugin:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      HOST: ${HOST:-plugins.nanome.ai}
      PORT: ${PORT:-9999}
  server:
    build:
      context: ../
      dockerfile: nanome_chemical_interactions/Dockerfile
