FROM continuumio/miniconda3

WORKDIR /app

RUN apt update && apt -y upgrade
RUN apt -y install build-essential python-openbabel vim

# Create the environment:
COPY environment.yml .
RUN conda env create -f environment.yml
RUN echo 'source activate arpeggio' >> /root/.bashrc
# Make RUN commands use the new environment:
SHELL ["conda", "run", "-n", "arpeggio", "/bin/bash", "-c"]

RUN pip install git+https://github.com/PDBeurope/arpeggio.git@master#egg=arpeggio
