name: Bump version workflow

on:
  push:
    branches:
    - version-fork

jobs:
  bump-version:
    name: Bump package version
    if: "!contains(github.event.head_commit.message, 'Bump version')"
    runs-on: ubuntu-20.04
    steps:
    - name: actions/checkout
      uses: actions/checkout@v2
      with:
          persist-credentials: false
    - name: run version script
      run: >
        pip install bump2version &&
        chmod +x ./version.sh &&
        ./version.sh minor