name: Deploy to PROD.
on:
  release:
    types: [published]

jobs:
  build:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Latest Tag
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PLUGINS_HQ_HOST }}
        port: ${{ secrets.PLUGINS_HQ_PORT }}
        username: ${{ secrets.PLUGINS_HQ_USERNAME }}
        key: ${{ secrets.PLUGINS_HQ_SECRET_KEY }}
        script: |
          cd ${{ secrets.PLUGINS_HQ_PROD_PATH }}
          git fetch --tags
          latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo $latestTag
          git checkout $latestTag
          cd docker
          ./build.sh
          ./deploy.sh
