name: Deploy to DEV.
on:
  push:
    branches: [master]
jobs:
  # bump-version:
  #   name: Bump package version
  #   if: "!contains(github.event.head_commit.message, 'Bump version')"
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - name: actions/checkout
  #     uses: actions/checkout@v2
  #     with:
  #         persist-credentials: true
  #   - name: run version script, bump version, and push commit to master
  #     run: >
  #       git config --global user.email "hello@nanome.ai"
  #       && git config --global user.name "Nanome"
  #       && pip install bump2version
  #       && chmod +x ./version.sh
  #       && ./version.sh patch
  #       && current_version=$(cat chem_interactions/__init__.py | grep __version__ | cut -d'=' -f2 | xargs)
  #       && git push origin master
  #       && git push origin v$current_version
  deploy:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    # needs: bump-version
    steps:
    - name: Fetch, Pull, Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PLUGINS_HQ_HOST }}
        username: ${{ secrets.PLUGINS_HQ_USERNAME }}
        key: ${{ secrets.PLUGINS_HQ_SECRET_KEY }}
        port: ${{ secrets.PLUGINS_HQ_PORT }}
        script: |
          cd ${{ secrets.PLUGINS_HQ_DEV_PATH }}
          git fetch
          git pull
          docker-compose build
          docker-compose -f docker-compose-deploy.yml -f docker-compose.override.yml --env-file .env up -d
