name: Push to ECR Registry

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Tag to use for image. Defaults to $GITHUB_REF
        required: False
  workflow_call:
    inputs:
      tag:
        type: string
        description: Tag to use for image. Defaults to $GITHUB_REF
        required: False
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      INPUT_PATH: "."
    steps:
    - uses: actions/checkout@v2.2.0
    - name: Get repo name
      id: repoName
      run: |
        prefix=nanome-ai/plugin-
        git_repository="${{github.repository}}"
        repo_name=${git_repository/#$prefix} 
        echo $repo_name
        echo "::set-output name=repo_name::$(echo $repo_name)"
    - name: Set default tag
      id: default_tag
      run: |
        default_tag="${GITHUB_REF#refs/*/}"
        echo Default tag = $default_tag
        echo "::set-output name=default_tag::$default_tag"
    - name: Get short SHA
      id: sha7
      run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
    - name: Get tag
      id: tag
      run: |
        input_tag=${{ inputs.tag }}
        echo "::set-output name=tag::$input_tag"
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build and Push to ECR public
      id: build-and-push
      uses: pahud/ecr-public-action@8cd826db40befb59b0cd0b60b22a7ba72d06a7f7
      with:
        dockerfile: docker/Dockerfile
        context: .
        tags: |
          public.ecr.aws/h7r1e4h2/${{ steps.repoName.outputs.repo_name }}:${{ steps.tag.outputs.tag }}
          public.ecr.aws/h7r1e4h2/${{ steps.repoName.outputs.repo_name }}:${{ steps.sha7.outputs.sha7 }}
