name: Validate Pull Requests
on:
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: pip install -r requirements.txt
    - run: conda env update -f arpeggio_environ.yml
    - run: python run_tests.py
