name: Update nanome-lib

on:
  workflow_dispatch:
    inputs:
      version_number:
        type: string
        description: nanome-lib version (e.g `0.34.8`)

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.NANOME_BOT_PAT }}
      - name: Bump Version
        run: |
          git config --global user.name 'nanome-bot'
          git config --global user.email '45469149+nanome-bot@users.noreply.github.com'
          sed 's/^nanome.*/nanome==${{ github.event.inputs.version }}/' requirements.txt
          git push --follow-tags
